### ISSUE TITLE
webpack warnings

### ISSUE THREAD

**Issue by rui-cruz** [rd-dev-ukraine/angular-io-overlay#3]
Hi,

It is possible to get rid of this warnings?

> WARNING in ./node_modules/angular-io-overlay/src/overlay/index.js
(Emitted value instead of an instance of Error) Cannot find source file 'index.ts': Error: Can't resolve './index.ts' in '\app\node_modules\angular-io-overlay\src\overlay'
 @ ./src/app/app.module.ts 21:0-51
 @ ./src/main.ts
 @ multi ./src/main.ts
WARNING in ./node_modules/angular-io-overlay/src/overlay/overlayService.js
(Emitted value instead of an instance of Error) Cannot find source file 'overlayService.ts': Error: Can't resolve './overlayService.ts' in '\app\node_modules\angular-io-overlay\src\over
lay'
 @ ./node_modules/angular-io-overlay/src/overlay/index.js 6:9-36
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
WARNING in ./node_modules/angular-io-overlay/src/overlay/overlayHostComponent.js
(Emitted value instead of an instance of Error) Cannot find source file 'overlayHostComponent.ts': Error: Can't resolve './overlayHostComponent.ts' in '\app\node_modules\angular-io-over
lay\src\overlay'
 @ ./node_modules/angular-io-overlay/src/overlay/index.js 7:9-42
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
WARNING in ./node_modules/angular-io-overlay/src/overlay/overlay.module.js
(Emitted value instead of an instance of Error) Cannot find source file 'overlay.module.ts': Error: Can't resolve './overlay.module.ts' in '\app\node_modules\angular-io-overlay\src\over
lay'
 @ ./node_modules/angular-io-overlay/src/overlay/index.js 9:9-36
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
WARNING in ./node_modules/angular-io-overlay/src/overlay/overlayComponent.js
(Emitted value instead of an instance of Error) Cannot find source file 'overlayComponent.ts': Error: Can't resolve './overlayComponent.ts' in '\app\node_modules\angular-io-overlay\src\
overlay'
 @ ./node_modules/angular-io-overlay/src/overlay/index.js 10:9-38
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
WARNING in ./node_modules/angular-io-overlay/src/overlay/positioning.js
(Emitted value instead of an instance of Error) Cannot find source file 'positioning.ts': Error: Can't resolve './positioning.ts' in '\app\node_modules\angular-io-overlay\src\overlay'
 @ ./node_modules/angular-io-overlay/src/overlay/index.js 8:9-33
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

Thank you very much for this lib!

**Comment by eugenesaenko** [comment]
Not reproduced.
