### ISSUE TITLE
 No provider for ComponentFactoryResolver!

### ISSUE THREAD

**Issue by SandeepDesu** [rd-dev-ukraine/angular-io-overlay#7]
Hi Team,
when i insert host in html page i got this error
![screen shot 2018-01-23 at 3 09 11 am](https://user-images.githubusercontent.com/17448101/35272637-d464b2e0-ffea-11e7-9e75-50d8a7ae3e37.png)
![screen shot 2018-01-23 at 3 08 57 am](https://user-images.githubusercontent.com/17448101/35272642-d7033b2a-ffea-11e7-9c1b-aa5c1bfb2d3d.png)

**Comment by egdraper** [comment]
Did you ever resolve this?

**Comment by SandeepDesu** [comment]
hi egdraper,
    resolved my issue.
